scenario_cfg:
  dataset_name: MME
  base_data_path: ../data/MME

eval_cfg:
  instruction_cfg: 
    prompt_type: singleturn
    prompt_assigned_ids: 2
    template_assigned_ids: 0
  inferencer_cfg:
    inferencer_type: Direct
    batch_size: 8
  metric_cfg:
    metric_type: basic