scenario_cfg:
  dataset_name: MME
  base_data_path: ../data/MME
  ppl_cfg: True
  option_lower: True

eval_cfg:
  instruction_cfg: 
    prompt_type: singleturn
    prompt_assigned_ids: 2
    template_assigned_ids: 0
  inferencer_cfg:
    inferencer_type: PPL
    batch_size: 8
  metric_cfg:
    metric_type: basic