scenario_cfg:
  dataset_name: CIFAR10
  base_data_path: ../data/LAMM/2D_Benchmark
eval_cfg:
  instruction_cfg: 
    prompt_type: singleturn
  inferencer_cfg:
    inferencer_type: Direct
    max_new_tokens: 16
    batch_size: 32
  metric_cfg:
    metric_type: basic