scenario_cfg:
  dataset_name: FSC147
  base_data_path: ../data/LAMM/2D_Benchmark
  ppl_cfg: 
    heatmap_width: 2

eval_cfg:
  instruction_cfg:
    prompt_type: singleturn
  inferencer_cfg:
    inferencer_type: PPL
    batch_size: 8
  metric_cfg:
    metric_type: basic
    inference_type: ppl