scenario_cfg:
  dataset_name: Flickr30k
  base_data_path: ../data/LAMM/2D_Benchmark
  ppl_cfg:
    negative_opt_num: 3
    random_seed: 0
    strategy: top_similarity
    model_path: ../model_zoo/all-MiniLM-L6-v2

eval_cfg:
  instruction_cfg:
    prompt_type: singleturn
  inferencer_cfg:
    inferencer_type: PPL
    batch_size: 4
  metric_cfg:
    metric_type: basic
    strategy: acc