scenario_cfg:
  dataset_name: VOC2012
  base_data_path: ../data/LAMM/2D_Benchmark

eval_cfg:
  instruction_cfg:
    prompt_type: multiturn
  inferencer_cfg:
    inferencer_type: Multi_Direct
    max_new_tokens: 64
    batch_size: 16
  metric_cfg:
    metric_type: basic