scenario_cfg:
  dataset_name: VOC2012
  base_data_path: ../data/LAMM/2D_Benchmark
  multi_turn: False
   
eval_cfg:
  instruction_cfg:
    prompt_type: singleturn
    prompt_assigned_ids: 1
  inferencer_cfg:
    inferencer_type: Direct
    max_new_tokens: 512
    batch_size: 8
  metric_cfg:
    metric_type: basic