scenario_cfg:
  dataset_name: Omnibenchmark
  base_data_path: ../data/ChEF/OmniBenchmark_Bamboo
  bamboo_tree_path: ../data/Bamboo/sensexo_visual_add_academic_add_state_V4.visual.json
  ppl_cfg: 
    negative_opt_num: 3
    random_seed: 0
  multiturn: False

eval_cfg:
  instruction_cfg: 
    prompt_type: singleturn
  inferencer_cfg:
    inferencer_type: PPL
    batch_size: 8
  metric_cfg:
    metric_type: basic
    inference_type: singleturn
    ppl: True
    bamboo_tree_path: ../data/Bamboo/sensexo_visual_add_academic_add_state_V4.visual.json
