scenario_cfg:
  dataset_name: MMMU
  base_data_path: ../data/MMMU
  img_folder: ../data/MMMU_images

eval_cfg:
  instruction_cfg:
    prompt_type: singleturn
  inferencer_cfg:
    inferencer_type: Direct
    batch_size: 1
    max_new_tokens: 256
  metric_cfg:
    metric_type: MMMU