scenario_cfg:
  dataset_name: ScienceQA
  base_data_path: ../data/LAMM/2D_Benchmark
  ppl: True
  option_content: False

eval_cfg:
  instruction_cfg: 
    prompt_type: singleturn
    prompt_assigned_ids: 0
    template_assigned_ids: 0
  inferencer_cfg:
    inferencer_type: PPL
    batch_size: 2
    CoT: True
    max_new_tokens: 128
  metric_cfg:
    metric_type: basic
