scenario_cfg:
  dataset_name: HHH
  base_data_path: ../data/ChEF_beta
  dimension: autodrive

eval_cfg:
  instruction_cfg:
    query_type: singleturn
  inferencer_cfg:
    inferencer_type: Direct
    batch_size: 8
    CoT: True
    max_new_tokens: 256
  metric_cfg:
    metric_type: HHH