scenario_cfg:
  dataset_name: HHH
  base_data_path: ../data/ChhhEF
  dimension: Helpful

eval_cfg:
  instruction_cfg:
    prompt_type: singleturn
  inferencer_cfg:
    inferencer_type: Direct
    batch_size: 8
    max_new_tokens: 256
  metric_cfg:
    metric_type: HHH