scenario_cfg:
  dataset_name: MMBench
  base_data_path: ../data/MMBench
  ppl_cfg: 
    content_only: False
  split: dev
  hint: True

eval_cfg:
  instruction_cfg: 
    prompt_type: singleturn 
    prompt_assigned_ids: 1 # (kosmos: 5) (default: 1) 
    template_assigned_ids: 1 # (kosmos: 0) (default: 1) 
    incontext_cfg:
      retriever_type: random
      ice_num: 1
      random_seed: 1
  inferencer_cfg:
    inferencer_type: PPL
    batch_size: 1
    CoT: False
    max_new_tokens: 256
  metric_cfg:
    metric_type: basic